server:
  port: 80
spring:
  application:
    name: zlikun-travis-sample
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
logging:
  level:
    root: info